version: '3.3'
services:
  mariadb:
    env_file: .env
    build: requirements/mariadb
    container_name: mariadb
    volumes:
      - vol_mariadb:/var/lib/mysql
    restart: unless-stopped
    networks:
      - inception
  wordpress:
    env_file: .env
    build: requirements/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - vol_wordpress:/var/www/html
    restart: on-failure
    networks:
      - inception
  nginx:
    env_file: .env
    build: requirements/nginx
    container_name: nginx
    depends_on:
      - wordpress
      - mariadb
    ports:
      - 443:443
    volumes:
      - vol_wordpress:/var/www/html
    restart: on-failure
    networks:
      - inception

networks:
  inception:
    driver: bridge

volumes:
  vol_mariadb:
    external: false
    driver: local
    driver_opts:
      type: ext4
      o: bind,rw
      device: /home/larmenou/data/vol_mariadb
  vol_wordpress:
    external: false
    driver: local
    driver_opts:
      type: ext4
      o: bind,rw
      device: /home/larmenou/data/vol_wordpress
