version: '3.3'
services:
  nginx:
    env_file: .env
    build: requirements/nginx
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - "./web:/var/www/html"
    restart: on-failure
    networks:
      - inception
  wordpress:
    env_file: .env
    build: requirements/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - "./web:/var/www/html"
    restart: on-failure
    networks:
      - inception
  mariadb:
    env_file: .env
    build: requirements/mariadb
    container_name: mariadb
    volumes:
      - "./database:/var/lib/mysql"
    restart: unless-stopped
    networks:
      - inception

networks:
  inception:
    driver: bridge

volumes:
  vol_mariadb:
    external: false
    driver: local
    driver_opts:
      type: 'ext4'
      o: 'bind,rw'
      device: '/home/larmenou/Documents/srcs/vol_mariadb'
  vol_wordpress:
    external: false
    driver: local
    driver_opts:
      type: 'ext4'
      o: 'bind,rw'
      device: '/home/larmenou/Documents/srcs/vol_wordpress'
